# Generated by Django 4.1.7 on 2023-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riddle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
