# Generated by Django 4.1.7 on 2023-03-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riddle_app', '0002_alter_riddle_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riddle',
            old_name='category',
            new_name='difficulty',
        ),
    ]
